servers:
  zta1:
    name: "Olympa ZTA"
    description: "Découvrez un monde au bord du chaos, meurtri par des hordes de zombies. Votre mission : survivre coûte que coûte, défendre votre clan et attaquer ceux des autres. Farmez et devenez l'homme le plus puissant de Greenfield !"
    item: FIREWORK_ROCKET
  pvpfac1:
    name: "Factions"
    description: "Créez votre faction avec vos amis, fabriquez des usines, des équipements, les bases les plus impénétrables possible et attaquez celles des autres. Battez vos ennemis et construisez un véritable empire pour accumuler les richesses, et devenez la plus grand faction de ce monde !"
    item: GOLDEN_HELMET
  creatif:
    name: "Créatif"
    description: "Le créatif est un mode de jeux vous permettant d'exprimer au plus profond votre imagination. Créez des constructions toujours plus grandes et plus belles les unes que les autres, jouez avec vos amis en incarnant des personnages et en créant vos propres histoires."
    item: GRASS_BLOCK
    
zone:
  ==: fr.olympa.api.region.shapes.Cuboid
  world: "world"
  xMin: -1000
  yMin: 0
  zMin: -1000
  xMax: 1000
  yMax: 256
  zMax: 1000